function M = Upsilon(theta)

% M = [cos(theta) -sin(theta) 0;...
%      sin(theta) cos(theta)  0;...
%      0             0        1];

M = [1      0            0;...
     0 cos(theta)  -sin(theta);...
     0 sin(theta)   cos(theta)];

end